/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPracticeIndexRouteImport } from './routes/_app.practice.index'
import { Route as AppLocumIndexRouteImport } from './routes/_app.locum.index'
import { Route as AppPracticeShiftsRouteImport } from './routes/_app.practice.shifts'
import { Route as AppPracticePracticesRouteImport } from './routes/_app.practice.practices'
import { Route as AppPracticePostRouteImport } from './routes/_app.practice.post'
import { Route as AppPracticeHoursRouteImport } from './routes/_app.practice.hours'
import { Route as AppLocumProfileRouteImport } from './routes/_app.locum.profile'
import { Route as AppLocumFindRouteImport } from './routes/_app.locum.find'
import { Route as AppLocumBookingsRouteImport } from './routes/_app.locum.bookings'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPracticeIndexRoute = AppPracticeIndexRouteImport.update({
  id: '/practice/',
  path: '/practice/',
  getParentRoute: () => AppRoute,
} as any)
const AppLocumIndexRoute = AppLocumIndexRouteImport.update({
  id: '/locum/',
  path: '/locum/',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeShiftsRoute = AppPracticeShiftsRouteImport.update({
  id: '/practice/shifts',
  path: '/practice/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticePracticesRoute = AppPracticePracticesRouteImport.update({
  id: '/practice/practices',
  path: '/practice/practices',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticePostRoute = AppPracticePostRouteImport.update({
  id: '/practice/post',
  path: '/practice/post',
  getParentRoute: () => AppRoute,
} as any)
const AppPracticeHoursRoute = AppPracticeHoursRouteImport.update({
  id: '/practice/hours',
  path: '/practice/hours',
  getParentRoute: () => AppRoute,
} as any)
const AppLocumProfileRoute = AppLocumProfileRouteImport.update({
  id: '/locum/profile',
  path: '/locum/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppLocumFindRoute = AppLocumFindRouteImport.update({
  id: '/locum/find',
  path: '/locum/find',
  getParentRoute: () => AppRoute,
} as any)
const AppLocumBookingsRoute = AppLocumBookingsRouteImport.update({
  id: '/locum/bookings',
  path: '/locum/bookings',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/locum/bookings': typeof AppLocumBookingsRoute
  '/locum/find': typeof AppLocumFindRoute
  '/locum/profile': typeof AppLocumProfileRoute
  '/practice/hours': typeof AppPracticeHoursRoute
  '/practice/post': typeof AppPracticePostRoute
  '/practice/practices': typeof AppPracticePracticesRoute
  '/practice/shifts': typeof AppPracticeShiftsRoute
  '/locum/': typeof AppLocumIndexRoute
  '/practice/': typeof AppPracticeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/locum/bookings': typeof AppLocumBookingsRoute
  '/locum/find': typeof AppLocumFindRoute
  '/locum/profile': typeof AppLocumProfileRoute
  '/practice/hours': typeof AppPracticeHoursRoute
  '/practice/post': typeof AppPracticePostRoute
  '/practice/practices': typeof AppPracticePracticesRoute
  '/practice/shifts': typeof AppPracticeShiftsRoute
  '/locum': typeof AppLocumIndexRoute
  '/practice': typeof AppPracticeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/locum/bookings': typeof AppLocumBookingsRoute
  '/_app/locum/find': typeof AppLocumFindRoute
  '/_app/locum/profile': typeof AppLocumProfileRoute
  '/_app/practice/hours': typeof AppPracticeHoursRoute
  '/_app/practice/post': typeof AppPracticePostRoute
  '/_app/practice/practices': typeof AppPracticePracticesRoute
  '/_app/practice/shifts': typeof AppPracticeShiftsRoute
  '/_app/locum/': typeof AppLocumIndexRoute
  '/_app/practice/': typeof AppPracticeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/locum/bookings'
    | '/locum/find'
    | '/locum/profile'
    | '/practice/hours'
    | '/practice/post'
    | '/practice/practices'
    | '/practice/shifts'
    | '/locum/'
    | '/practice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/locum/bookings'
    | '/locum/find'
    | '/locum/profile'
    | '/practice/hours'
    | '/practice/post'
    | '/practice/practices'
    | '/practice/shifts'
    | '/locum'
    | '/practice'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/sitemap.xml'
    | '/_app/locum/bookings'
    | '/_app/locum/find'
    | '/_app/locum/profile'
    | '/_app/practice/hours'
    | '/_app/practice/post'
    | '/_app/practice/practices'
    | '/_app/practice/shifts'
    | '/_app/locum/'
    | '/_app/practice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/practice/': {
      id: '/_app/practice/'
      path: '/practice'
      fullPath: '/practice/'
      preLoaderRoute: typeof AppPracticeIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locum/': {
      id: '/_app/locum/'
      path: '/locum'
      fullPath: '/locum/'
      preLoaderRoute: typeof AppLocumIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/shifts': {
      id: '/_app/practice/shifts'
      path: '/practice/shifts'
      fullPath: '/practice/shifts'
      preLoaderRoute: typeof AppPracticeShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/practices': {
      id: '/_app/practice/practices'
      path: '/practice/practices'
      fullPath: '/practice/practices'
      preLoaderRoute: typeof AppPracticePracticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/post': {
      id: '/_app/practice/post'
      path: '/practice/post'
      fullPath: '/practice/post'
      preLoaderRoute: typeof AppPracticePostRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/practice/hours': {
      id: '/_app/practice/hours'
      path: '/practice/hours'
      fullPath: '/practice/hours'
      preLoaderRoute: typeof AppPracticeHoursRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locum/profile': {
      id: '/_app/locum/profile'
      path: '/locum/profile'
      fullPath: '/locum/profile'
      preLoaderRoute: typeof AppLocumProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locum/find': {
      id: '/_app/locum/find'
      path: '/locum/find'
      fullPath: '/locum/find'
      preLoaderRoute: typeof AppLocumFindRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/locum/bookings': {
      id: '/_app/locum/bookings'
      path: '/locum/bookings'
      fullPath: '/locum/bookings'
      preLoaderRoute: typeof AppLocumBookingsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLocumBookingsRoute: typeof AppLocumBookingsRoute
  AppLocumFindRoute: typeof AppLocumFindRoute
  AppLocumProfileRoute: typeof AppLocumProfileRoute
  AppPracticeHoursRoute: typeof AppPracticeHoursRoute
  AppPracticePostRoute: typeof AppPracticePostRoute
  AppPracticePracticesRoute: typeof AppPracticePracticesRoute
  AppPracticeShiftsRoute: typeof AppPracticeShiftsRoute
  AppLocumIndexRoute: typeof AppLocumIndexRoute
  AppPracticeIndexRoute: typeof AppPracticeIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLocumBookingsRoute: AppLocumBookingsRoute,
  AppLocumFindRoute: AppLocumFindRoute,
  AppLocumProfileRoute: AppLocumProfileRoute,
  AppPracticeHoursRoute: AppPracticeHoursRoute,
  AppPracticePostRoute: AppPracticePostRoute,
  AppPracticePracticesRoute: AppPracticePracticesRoute,
  AppPracticeShiftsRoute: AppPracticeShiftsRoute,
  AppLocumIndexRoute: AppLocumIndexRoute,
  AppPracticeIndexRoute: AppPracticeIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
